name: tanfeth_apps
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  get_storage: ^2.1.1
  intl: ^0.19.0
  http: ^1.1.0
  connectivity_plus: ^5.0.1
  upgrader: ^8.2.0
  image_picker: ^1.0.4
  #========= firebase ================================
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.2
  flutter_local_notifications: ^17.2.1+2
  #========= firebase ================================
  flutter_svg: ^2.0.7
  pinput: ^3.0.1
  flutter_widget_from_html: ^0.10.6
  shimmer: ^3.0.0
  url_launcher: ^6.1.14
  oktoast: ^3.3.2
  badges: ^3.1.2
  carousel_slider_plus: ^7.0.0
  flutter_rating_bar: ^4.0.1
  file_picker: ^6.0.0
  open_filex: ^4.3.4
  path_provider: ^2.1.1
  json_annotation: ^4.9.0
  #====== google map ======================================
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  geocoding: ^2.1.1
  #====== google map ======================================
  line_icons: ^2.0.3
  share_plus: ^7.2.0
  store_redirect: ^2.0.1
  sqflite: ^2.3.0
  percent_indicator: ^4.2.3
  flutter_staggered_grid_view: ^0.7.0
  package_info_plus: ^4.2.0
  permission_handler: ^11.0.1
  webview_flutter: ^4.4.1
  path: ^1.8.3
  flutter_markdown: ^0.6.18+2
  printing: ^5.12.0
  pdf: ^3.10.8
  country_picker: ^2.0.26
  animated_notch_bottom_bar: ^1.0.3
  floating_draggable_widget: ^2.1.5
  flutter_riverpod: ^2.5.1
  showcaseview: ^3.0.0
  flutter_localization: ^0.2.0
  timeago: ^3.6.1
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  json_model: ^1.0.0
  build_runner: ^2.4.6
  flutter_image_compress: ^2.3.0
  dio: ^5.4.3+1
  flutter_secure_storage: ^9.2.2
  http_parser: ^4.0.2
  mime: ^1.0.5
  shared_preferences: ^2.2.3
  internet_connection_checker: ^1.0.0+1
  fluttertoast: ^8.2.5
  signalr_core: ^1.1.2
  signalr_netcore: ^1.3.7
  sse_channel2: ^0.0.4
  uuid: ^3.0.7
  lottie: ^3.1.2
  jhijri: any
  jhijri_picker: any
  facebook_app_events: ^0.19.0
  uni_links: ^0.5.1
  firebase_analytics: ^11.1.0
  widget_zoom: ^0.0.4
  dropdown_search: ^5.0.6
  shelf: ^1.4.2
  top_modal_sheet: ^2.1.0
  fl_chart: ^0.68.0
  flutter_native_contact_picker: ^0.0.6
  flutter_google_places: ^0.3.0
  flutter_polyline_points: ^2.0.1
  animate_do: ^3.3.4
  firebase_crashlytics: ^4.0.2
  ffi: ^2.1.2
  device_info_plus: ^10.1.0
  searchable_paginated_dropdown: ^1.3.0
  cuberto_bottom_bar: ^3.1.0
  api_controller:
    git:
      url: git@github.com:abdomobarak/api_controller.git




dependency_overrides:
  meta: ^1.14.0
  flutter_localization: ^0.2.0
  timeago: ^3.6.1
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^17.2.1+2
  json_model: ^1.0.0
  build_runner: ^2.4.6
  flutter_image_compress: ^2.3.0
  flutter_secure_storage: ^9.2.2
  http_parser: ^4.0.2
  mime: ^1.0.5
  shared_preferences: ^2.2.3
  internet_connection_checker: ^1.0.0+1
  flutter_screenutil: ^5.9.1
  country_picker: ^2.0.17
  fluttertoast: ^8.2.5
  signalr_core: ^1.1.2
  signalr_netcore: ^1.3.7
  sse_channel2: ^0.0.4
  uuid: ^3.0.7
  lottie: ^3.1.2
  jhijri: any
  jhijri_picker: any
  facebook_app_events: ^0.19.0
  uni_links: ^0.5.1
  firebase_analytics: ^11.1.0
  widget_zoom: ^0.0.4
  dropdown_search: ^5.0.6
  showcaseview: ^3.0.0
  shelf: ^1.4.2
  top_modal_sheet: ^2.1.0
  fl_chart: ^0.68.0
  flutter_native_contact_picker: ^0.0.6
  flutter_google_places: ^0.3.0
  http: ^0.13.1
  geocoding: ^3.0.0
  flutter_polyline_points: ^2.0.1
  animate_do: ^3.3.4
  firebase_crashlytics: ^4.0.2
  ffi: ^2.1.2
  dio: ^5.5.0+1


dev_dependencies:
  json_serializable: any
  lint: ^1.10.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7




flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/common/
    - assets/common/images/
    - assets/common/lottie/
    - assets/taxi24Driver/
    - assets/taxi24Driver/lottie/
    - assets/taxi24Passenger/
    - assets/taxi24Passenger/lottie/
    - assets/feedMe/
    - assets/feedMe/lottie/



  fonts:
    - family: DinNext
      fonts:
        - asset: assets/fonts/DinNext/din-next-lt-w23-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/DinNext/din-next-lt-w23-Light.ttf
          weight: 300
        - asset: assets/fonts/DinNext/din-next-lt-w23-Regular.ttf
          weight: 400
        - asset: assets/fonts/DinNext/din-next-lt-w23-Medium.ttf
          weight: 500
        - asset: assets/fonts/DinNext/din-next-lt-w23-Bold.ttf
          weight: 700
        - asset: assets/fonts/DinNext/din-next-lt-w23-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/DinNext/din-next-lt-w23-Black.ttf
          weight: 900


analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true