// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDh3EXuv85X-QAAh4bFxKBTc8JHxyICtQ',
    appId: '1:708944208533:android:07992daf4ea98a2eac319c',
    messagingSenderId: '708944208533',
    projectId: 'proud-guide-380707',
    databaseURL: 'https://proud-guide-380707-default-rtdb.firebaseio.com',
    storageBucket: 'proud-guide-380707.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf4_pSBB0bxJ5uQEMhH0V54K7ncBYj-HQ',
    appId: '1:708944208533:ios:93bcff1faabaff1dac319c',
    messagingSenderId: '708944208533',
    projectId: 'proud-guide-380707',
    databaseURL: 'https://proud-guide-380707-default-rtdb.firebaseio.com',
    storageBucket: 'proud-guide-380707.appspot.com',
    iosClientId: '708944208533-4vunr3u5hfnp09tlbaloeo79brrhf7kj.apps.googleusercontent.com',
    iosBundleId: 'com.taxi24.driver',
  );

}