import 'package:flutter/services.dart' as services;
import 'package:tanfeth_apps/common/shared/custom_methods.dart';

class Images {
  static String  appLogo = '';
  static String  locationLottie = '';
  static String  driverImage = '';
  static String  pickUpImg = '';
  static String  destinationImage = '';
  static String  mapCarImage = '';
  static String  navigationImage = '';
  static String  swipeIcon = '';
  static String  personWithSuccessImage = '';
  static String  saudiArabiaIconSVG = '';
  static String  appLogoSVG = '';
  static String  welcomeGroup10SVG = '';
  static String  welcomeGroup14SVG = '';
  static String  homeSVG = '';
  static String  personSVG = '';
  static String  walletSVG = '';
  static String  locationDetectorSVG = '';
  static String  userLocation = '';
  static String  formFieldCircleSVG = '';
  static String  heartSVG = '';
  static String  heartFilledSVG = '';
  static String  fullClockSVG = '';
  static String  locationPinSVG = '';
  static String  avatar = '';
  static String  downArrow = '';
  static String  pickUp = '';
  static String  avatarSVG = '';
  static String  downArrowSVG = '';
  static String  pickUpSVG = '';
  static String  percentageSVG = '';
  static String  carSVG = '';
  static String  cardSVG = '';
  static String  cashSVG = '';
  static String  locationSVG = '';
  static String  questionMarkSVG = '';
  static String  securityCodeCardSVG = '';
  static String  visaSVG = '';
  static String  arrowSVG = '';
  static String  arrowLeftSVG = '';
  static String  starSVG = '';
  static String  redStarSVG = '';
  static String  orangeStarSVG = '';
  static String  passengerSVG = '';
  static String  expiryDateCardSVG = '';
  static String  addRiderSVG = '';
  static String  addressBookSVG = '';
  static String  recentClock = '';
  static String  alertSVG = '';
  static String  becomeCaptainSVG = '';
  static String  editPenSVG = '';
  static String  helpSVG = '';
  static String  languageSVG = '';
  static String  personAvatarSVG = '';
  static String  privacySVG = '';
  static String  kStarSVG = '';
  static String  userWithMapSVG = '';
  static String  userWithRestSVG = '';
  static String  personInfoSVG = '';
  static String  rateAppSVG = '';
  static String  cardsSVG = '';
  static String  transactionsSVG = '';
  static String  tripCarSVG = '';
  static String  plusSVG = '';
  static String  plusIconSVG = '';
  static String  userWithMessageSVG = '';
  static String  mastercardSVG = '';
  static String  successSVG = '';
  static String  dotsSVG = '';
  static String  starIconSVG = '';
  static String  editIconSVG = '';
  static String  deleteIconSVG = '';
  static String  sendSVG = '';
  static String  englishSVG = '';
  static String  arabicSVG = '';
  static String  calendarSVG = '';
  static String  fileSVG = '';
  static String  driverCarSVG = '';
  static String  routeToSVG = '';
  static String  logOutSVG = '';
  static String  checkMarkSVG = '';
  static String  cameraSVG = '';
  static String  gallerySVG = '';
  static String  alertIconSVG = '';
  static String  walletProfileSVG = '';
  static String  earningsProfileSVG = '';
  static String  carProfileSVG = '';
  static String  documentProfileSVG = '';
  static String  settingProfileSVG = '';
  static String  aboutProfileSVG = '';
  static String  accsMarkSVG = '';
  static String  moreSVG = '';
  static String  closeSVG = '';
  static String  listSVG = '';
  static String  phoneSVG = '';
  static String  navigationArrowSVG = '';
  static String  bankSVG = '';
  static String  sendSettingsSVG = '';
  static String  bankCardSVG = '';
  static String  activitySVG = '';
  static String  checkMarkCircleSVG = '';
  static String  searchSVG = '';
  static String  errorSVG = '';
  static String  navigationOutlineSVG = '';




  static Future<void> initImages() async {
     appLogo = 'logo.png';
     locationLottie = 'location.json';
     driverImage = 'driver.png';
     pickUpImg = 'Pickupimg.png';
     destinationImage = 'destination.png';
     mapCarImage = 'map_car.png';
     navigationImage = 'navigation-arrow-icon.png';
     swipeIcon = 'swipe_icon.gif';
     personWithSuccessImage = 'person_with_success.png';
     saudiArabiaIconSVG = 'saudi-arabia.svg';
     appLogoSVG = 'logo.svg';
     welcomeGroup10SVG = 'welcome_group10.svg';
     welcomeGroup14SVG = 'welcome_group14.svg';
     homeSVG = 'home.svg';
     personSVG = 'person.svg';
     walletSVG = 'wallet.svg';
     locationDetectorSVG = 'location_detector.svg';
     userLocation = 'User_location.png';
     formFieldCircleSVG = 'form_field_circle.svg';
     heartSVG = 'heart.svg';
     heartFilledSVG = 'heart-filled-icon.svg';
     fullClockSVG = 'full_clock.svg';
     locationPinSVG = 'location_pin.svg';
     avatar = 'Avatar.svg';
     downArrow = 'chevron-down-icon.svg';
     pickUp = 'Pickup.svg';
     avatarSVG = 'Avatar.svg';
     downArrowSVG = 'chevron-down-icon.svg';
     pickUpSVG = 'Pickup.svg';
     percentageSVG = 'percentage.svg';
     carSVG = 'car.svg';
     cardSVG = 'card.svg';
     cashSVG = 'cash.svg';
     locationSVG = 'location.svg';
     questionMarkSVG = 'question_mark.svg';
     securityCodeCardSVG = 'security_code_card.svg';
     visaSVG = 'visa.svg';
     arrowSVG = 'chevron-right-icon.svg';
     arrowLeftSVG = 'chevron-left-icon.svg';
     starSVG = 'star.svg';
     redStarSVG = 'red_star.svg';
     orangeStarSVG = 'orange_star.svg';
     passengerSVG = 'passenger.svg';
     expiryDateCardSVG = 'expiry_date_card.svg';
     addRiderSVG = 'Add-a-rider.svg';
     addressBookSVG = 'address-book-icon.svg';
     recentClock = 'recent-clock.svg';
     alertSVG = 'alert.svg';
     becomeCaptainSVG = 'become_captain.svg';
     editPenSVG = 'edit_pen.svg';
     helpSVG = 'help.svg';
     languageSVG = 'language.svg';
     personAvatarSVG = 'person_avatar.svg';
     privacySVG = 'privacy.svg';
     kStarSVG = 'star.svg';
     userWithMapSVG = 'user_with_map.svg';
     userWithRestSVG = 'user_with_rest.svg';
     personInfoSVG = 'person_info.svg';
     rateAppSVG = 'rate_app.svg';
     cardsSVG = 'Cards.svg';
     transactionsSVG = 'Transactions.svg';
     tripCarSVG = 'trip_car.svg';
     plusSVG = 'plus.svg';
     plusIconSVG = 'plus_icon.svg';
     userWithMessageSVG = 'user_with_message.svg';
     mastercardSVG = 'Mastercard.svg';
     successSVG = 'Success.svg';
     dotsSVG = 'dots-icon.svg';
     starIconSVG = 'star-icon.svg';
     editIconSVG = 'edit-icon.svg';
     deleteIconSVG = 'delete-icon.svg';
     sendSVG = 'send.svg';
     englishSVG = 'english.svg';
     arabicSVG = 'saudi-arabia.svg';
     calendarSVG = 'calendar.svg';
     fileSVG = 'file.svg';
     driverCarSVG = 'driver_car.svg';
     routeToSVG = 'route_to.svg';
     logOutSVG = 'log_out.svg';
     checkMarkSVG = 'check_mark.svg';
     cameraSVG = 'camera.svg';
     gallerySVG = 'gallery.svg';
     alertIconSVG = 'alert-icon.svg';
     walletProfileSVG = 'wallet_profile.svg';
     earningsProfileSVG = 'earnings_profile.svg';
     carProfileSVG = 'car_profile.svg';
     documentProfileSVG = 'document_profile.svg';
     settingProfileSVG = 'setting_profile.svg';
     aboutProfileSVG = 'about_profile.svg';
     accsMarkSVG = 'accs_mark.svg';
     moreSVG = 'more.svg';
     closeSVG = 'close-icon.svg';
     listSVG = 'list-icon.svg';
     phoneSVG = 'phone-icon.svg';
     navigationArrowSVG = 'navigation-arrow-icon.svg';
     bankSVG = 'bank-icon.svg';
     sendSettingsSVG = 'send_settings.svg';
     bankCardSVG = 'Bank.svg';
     activitySVG = 'activity-icon.svg';
     checkMarkCircleSVG = 'checkmark-circle-icon.svg';
     searchSVG = 'search-icon.svg';
     errorSVG = 'error-icon.svg';
     navigationOutlineSVG = 'navigation_outline.svg';
  }

  static Future<String> checkImage(String path) async {
    var finalPath = "";
    try {
      if (isTaxi24Driver) {
        finalPath = "assets/images/$path";
      }
      await services.rootBundle.loadString(finalPath);
      return finalPath;
    } on FormatException {
      return finalPath;
    } catch (_) {
      return "assets/common/images/$path";
    }
  }
}
